ALL_KEYWORDS = list(set(
    MINIMIZE_MACRO_KEYS + PERTUMBUHAN_EKONOMI + INFLASI + EXIM + INVESTASI
))

MINIMIZE_MACRO_KEYS = [
    'dolar as',
    'rupiah dolar',
    "rupiah dolar as",
    'ekspor kopi',
    'ekspor sawit',
    'gaji ke-13',
    'gaji pns',
    'harga bawang merah',
    'harga bawang putih',
    'harga beras',
    'harga cabai',
    'harga kakao',
    'harga karet',
    'harga komoditas',
    'harga kopi',
    'harga minyak goreng',
    'harga pupuk',
    'harga rokok',
    'harga sawit',
    'harga sembako',
    'inflasi',
    'kenaikan harga',
    'konsumsi kakao',
    'konsumsi komoditas global',
    'konsumsi kopi',
    'konsumsi sawit',
    'kurs rupiah',
    'nilai tukar petani',
    'pdb',
    "suku bunga",
    "kredit otomotif",
    "kredit motor",
    "harga motor",
    "pajak motor",
    'pertumbuhan ekonomi',
    'produk domestik bruto',
    'produksi kakao',
    'produksi karet',
    'produksi komoditas',
    'produksi kopi',
    'produksi padi',
    'produksi sawit',
    'thr',
    'umr'
]
PERTUMBUHAN_EKONOMI = [
    'anggaran kementerian',
    'anggaran negara',
    'apbn',
    'apbn perubahan',
    'bangkrut',
    'belanja kementerian',
    'belanja masyarakat',
    'belanja negara',
    'belanja pemerintah',
    'biaya pendidikan',
    'biaya sekolah',
    'daya beli masyarakat',
    'defisit anggaran',
    'ekonomi dunia',
    'ekonomi global',
    'ekonomi tumbuh',
    'gaji ke-13',
    'gaji naik',
    'gaji pegawai negeri',
    'gaji pns',
    'impor barang modal',
    'industri manufaktur',
    'industri otomotif',
    'industri tekstil',
    'investasi asing ',
    'investasi dalam negeri',
    'kenaikan gaji',
    'kenaikan pajak',
    'keyakinan konsumen',
    'konsumsi masyarakat',
    'korupsi',
    'lowongan kerja',
    'pailit',
    'pajak naik',
    'penanaman modal dalam negeri',
    'pendapatan masyarakat',
    'penerimaan pajak',
    'pengangguran',
    'pengangguran terbuka',
    'perbankan',
    'perdagangan',
    'perkebunan',
    'pertanian',
    'pertumbuhan ekonomi',
    'pmdn',
    'ppn naik',
    'proyeksi ekonomi',
    'rapbn',
    'resesi ekonomi',
    'suku bunga bank sentral',
    'thr',
    'tunjangan hari raya',
    'uang beredar',
    'umk',
    'umr',
    'upah',
    'utang pemerintah'
]
INFLASI = [
    'cukai rokok',
    'deflasi',
    'harga avtur',
    'harga barang',
    'harga batu bara',
    'harga bawang merah',
    'harga bawang putih',
    'harga bbm',
    'harga beras',
    'harga cabai',
    'harga cabe',
    'harga coklat',
    'harga daging ayam',
    'harga daging sapi',
    'harga dex',
    'harga emas',
    'harga gas',
    'harga gas alam',
    'harga gula',
    'harga kopi',
    'harga minyak goreng',
    'harga minyak mentah (wti)',
    'harga pertalite',
    'harga pertamax',
    'harga pupuk',
    'harga rokok',
    'harga rumah',
    'harga sawit',
    'harga sembako',
    'harga solar',
    'harga teh',
    'harga telur',
    'harga tepung',
    'ihk',
    'indeks harga konsumen',
    'inflasi',
    'kenaikan harga',
    'kredit mobil',
    'kredit motor',
    'kur',
    'penjualam mobil',
    'penjualan motor',
    'penjualan semen',
    'sewa apartemen',
    'sewa rumah',
    'suku bunga bi',
    'suku bunga deposito',
    'suku bunga kpr',
    'suku bunga pinjaman',
    'suku bunga tabungan',
    'tarif listrik',
    'tarif tol',
    'tiket bus',
    'tiket kapal',
    'tiket kereta',
    'tiket pesawat',
    'uang beredar'
]
EXIM = [
    'aliran dana asing',
    'cadangan devisa',
    'defisit neraca perdagangan',
    'dolar amerika',
    'ekspor batu bara',
    'ekspor migas',
    'ekspor nonmigas',
    'ekspor sawit',
    'harga batubara',
    'harga cpo',
    'harga kelapa sawit ',
    'harga komoditas',
    'harga obligasi',
    'harga saham',
    'ihsg',
    'imbal hasil obligasi',
    'impor migas',
    'impor minyak',
    'impor nonmigas',
    'impor tekstil',
    'import demand ',
    'indeks harga saham',
    'investasi asing',
    'investor obligasi',
    'investor saham',
    'kemampuan cadangan devisa',
    'kurs dolar',
    'kurs rupiah',
    'neraca migas',
    'neraca perdagangan',
    'nilai ekspor',
    'nilai impor',
    'nilai tukar rupiah',
    'obligasi',
    'penanaman modal asing',
    'remitansi pekerja migran',
    'surplus neraca perdagangan',
    'tarif as',
    'tarif timbal balik',
    'tarif trump',
    'tekanan jual di pasar saham',
    'utang luar negeri',
    'yield obligasi'
]
INVESTASI = [
    'bursa',
    'cryptocurrency',
    'danantara',
    'diversifikasi pasar',
    'harga emas',
    'harga properti',
    'harga saham',
    'ihsg',
    'investasi',
    'investasi syariah',
    'kripto',
    'obligasi',
    'obligasi syariah',
    'ori',
    'pasar modal',
    'reksadana',
    'resesi',
    'sbn',
    'yield',
]
EN_INVESTASI = [
    "stock",
    "share",
    "bond",
    "equity",
    "fixed income",
    "real estate",
    "property market",
    "mutual fund",
    "etf",
    "hedge fund",
    "private equity",
    "venture capital",
    "cryptocurrency",
    "bitcoin",
    "ethereum",
    "digital asset",
    "nft",
    "commodity",
    "oil price",
    "gold",
    "inflation",
    "interest rate",
    "federal reserve",
    "central bank",
    "monetary policy",
    "market volatility",
    "economic growth",
    "recession fear",
    "supply chain issue",
    "geopolitical risk",
    "sustainability",
    "esg investing",
    "green bond",
    "renewable energy",
    "technology stock",
    "artificial intelligence",
    "electric vehicle",
    "emerging market",
    "developed market",
    "portfolio diversification",
    "risk management",
    "yield",
    "dividend",
    "market correction",
    "bull market",
    "bear market",
    "regulation",
    "ipo",
    "merger and acquisition",
    "investor sentiment",
    "financial market"
]